#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
from pathlib import Path

def get_dir():
    return Path(__file__).resolve().parent

def create_cpp(base, name):
    hdr_procon = open(base/"include"/"procon.hpp", "r").read()
    hdr_random = open(base/"include"/"random.hpp", "r").read()
    hdr_string = open(base/"include"/"string.hpp", "r").read()
    body = open(base/"tmpl"/"gen.cpp", "r").read()
    try:
        with open(name, "x") as out:
            out.write(hdr_procon)
            out.write("\n")
            out.write(hdr_random)
            out.write("\n")
            out.write(hdr_string)
            out.write(body)
        print(name)
    except FileExistsError:
        return;

def create_makefile(base):
    NAME = "Makefile"
    body = open(base/"tmpl"/"Makefile", "r").read()
    try:
        with open(NAME, "x") as out:
            out.write(body)
        print(NAME)
    except FileExistsError:
        return;

def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("name", nargs="?", default="gen.cpp")
    return ap.parse_args()

def main():
    args = parse_args()

    base = get_dir()

    create_cpp(base, args.name)
    create_makefile(base)

if __name__ == "__main__": main()
