#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
from pathlib import Path

def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("name")
    return ap.parse_args()

def main():
    args = parse_args()

    target = Path("test") / args.name
    target.mkdir()

    readme = target / "README.md"
    open(readme, "x").write(f"""\
# {target.name}


""")

    t = target / "t"
    open(t, "x").write("""\
#!/bin/sh

oj t 2>/dev/null
""")
    t.chmod(0o755)

    solve_cpp = target / "solve.cpp"
    open(solve_cpp, "x").write("""\
#include "procon.hpp"

signed main() {
    

    EXIT();
}
""")

    makefile = target / "Makefile"
    makefile.symlink_to("../Makefile.default")

if __name__ == "__main__": main()
